/**
 * Unified Skill interface for Cognitive Coordination.
 * Normalizes skills from Memory (consolidation) and Self-Evolution (extraction).
 */
export interface UnifiedSkill {
	id: string;
	source: "memory_consolidation" | "evolution_extraction" | "user_manual";
	name: string;
	content: string;
	confidenceScore: number;
	lastUsedAt: number;
	version: string;
	status: "active" | "deprecated" | "experimental";
	/** Additional metadata from the source system */
	metadata?: Record<string, unknown>;
}

/**
 * Context Injection payload for the Agent.
 * Constructed by the Context Assembler.
 */
export interface ContextInjection {
	memorySummary?: string;
	skills: UnifiedSkill[];
	conventions: string[];
}

/**
 * Skill Frontmatter schema for file-based skills.
 */
export interface SkillFrontmatter {
	name: string;
	version: string;
	source: "memory" | "evolution" | "manual";
	confidence_score: number;
	last_used_at: string;
	status: "active" | "deprecated" | "experimental";
	description?: string;
}

/**
 * Activity Trend Report generated by the Activity Monitor.
 */
export interface TrendReport {
	fitScoreTrend: {
		scores: number[];
		average: number;
		dateRange: { start: string; end: string };
	};
	skillDecay: Array<{ name: string; lastUsedAt: string | null; daysSinceLastUse: number }>;
	errorRate: {
		errorCount: number;
		totalEvents: number;
		rate: number;
	};
	analyzedAt: string;
}

/**
/**
 * Implicit Convention mined from Session Logs.
 */
export interface ProceduralRule {
	rule: string;
	confidence: number;
	sourceSessionId?: string;
	/** Provenance level for conflict resolution. Higher provenance wins on merge. */
	provenance?: "user_stated" | "implied" | "inferred" | "fallback";
	/** Timestamp of last update, for decay calculations. */
	updatedAt?: number;
	/** ID of the convention that superseded this one (audit trail). */
	supersededBy?: string;
	/** When this convention was superseded. */
	supersededAt?: number;
}
