/**
 * Narwal Plan static model seeds (https://coder.narwal.com/v1).
 *
 * <provider-models> 的静态种子：narwal 网关的 /v1/models 只返回裸 id，
 * 不携带 contextWindow/cost/reasoning/thinking 元数据。这份清单在 discovery
 * 合并（mapWithBundledReference / mergeDynamicModel）时作为 reference 补全元数据，
 * 并在 generate-models 时与动态模型合并后写入 models.json。
 *
 * Generated from ~/.cornfield/agent/models.yml providers.narwal-plan —— 保持与用户实测
 * 元数据一致。新增/变更模型时同步更新此处或依赖 discovery 裸条目（元数据为占位值）。
 */
import { Effort } from "../model-thinking";
import type { Model } from "../types";

export const NARWAL_PLAN_STATIC_MODELS: readonly Model<"openai-completions">[] = [
	{
		id: "glm-5.2",
		name: "GLM 5.2",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text"],
		cost: {
			input: 1.0,
			output: 3.0,
			cacheRead: 0.2,
			cacheWrite: 0,
		},
		contextWindow: 1000000,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "gpt-5.4",
		name: "GPT 5.4",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 2.5,
			output: 15.0,
			cacheRead: 0.25,
			cacheWrite: 0,
		},
		contextWindow: 1050000,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "gpt-5.5",
		name: "GPT 5.5",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 5.0,
			output: 30.0,
			cacheRead: 0.5,
			cacheWrite: 0,
		},
		contextWindow: 1050000,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "claude-opus-4.7",
		name: "Claude Opus 4.7",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 5.0,
			output: 25.0,
			cacheRead: 0.5,
			cacheWrite: 6.25,
		},
		contextWindow: 1000000,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "claude-opus-4.6",
		name: "Claude Opus 4.6",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 5.0,
			output: 25.0,
			cacheRead: 0.5,
			cacheWrite: 6.25,
		},
		contextWindow: 200000,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "claude-opus-4.8",
		name: "Claude Opus 4.8",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 5.0,
			output: 25.0,
			cacheRead: 0.5,
			cacheWrite: 6.25,
		},
		contextWindow: 1000000,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "claude-sonnet-4.6",
		name: "Claude Sonnet 4.6",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 3.0,
			output: 15.0,
			cacheRead: 0.3,
			cacheWrite: 3.75,
		},
		contextWindow: 1000000,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "minimax-m2.7",
		name: "Minimax M2.7",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 0.3,
			output: 1.2,
			cacheRead: 0.06,
			cacheWrite: 0.375,
		},
		contextWindow: 200000,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "minimax-m3",
		name: "Minimax M3",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 0.6,
			output: 2.4,
			cacheRead: 0.12,
			cacheWrite: 0.75,
		},
		contextWindow: 1000000,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "xiaomi/mimo-v2.5-pro",
		name: "Xiaomi Mimo V2.5 Pro",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 1.0,
			output: 3.0,
			cacheRead: 0.2,
			cacheWrite: 0,
		},
		contextWindow: 1000000,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "custom-model-b1-standard",
		name: "Custom Model B1 Standard",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text"],
		cost: {
			input: 0,
			output: 0,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 1050000,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "custom-model-b3-standard",
		name: "Custom Model B3 Standard",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text"],
		cost: {
			input: 0,
			output: 0,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 390000,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "custom-model-b5-standard",
		name: "Custom Model B5 Standard",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text"],
		cost: {
			input: 0,
			output: 0,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 1050000,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "custom-model-c1",
		name: "Custom Model C1",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text"],
		cost: {
			input: 0,
			output: 0,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 1048576,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "custom-model-c2-flash",
		name: "Custom Model C2 Flash",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text"],
		cost: {
			input: 0,
			output: 0,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 1048576,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "qwen3.6-flash",
		name: "Qwen 3.6 Flash",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text"],
		cost: {
			input: 0.1,
			output: 0.4,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 1000000,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "qwen3.6-plus",
		name: "Qwen 3.6 Plus",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 0.25,
			output: 1.5,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 1000000,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "qwen3.7-max",
		name: "Qwen 3.7 Max",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 2.77,
			output: 8.31,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 1000000,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "qwen3.7-plus",
		name: "Qwen 3.7 Plus",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 0.44,
			output: 1.77,
			cacheRead: 0.08,
			cacheWrite: 0.5,
		},
		contextWindow: 1000000,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "claude-haiku-4-5-20251001",
		name: "Claude Haiku 4.5",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 1.0,
			output: 5.0,
			cacheRead: 0.1,
			cacheWrite: 0,
		},
		contextWindow: 1000000,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "custom-model-b2-cx",
		name: "Custom Model B2 CX",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text"],
		cost: {
			input: 0,
			output: 0,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 390000,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "deepseek-v4-pro",
		name: "DeepSeek V4 Pro",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text"],
		cost: {
			input: 0.435,
			output: 0.87,
			cacheRead: 0.08,
			cacheWrite: 0,
		},
		contextWindow: 1000000,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "deepseek-v4-flash",
		name: "DeepSeek V4 Flash",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text"],
		cost: {
			input: 0.14,
			output: 0.28,
			cacheRead: 0.03,
			cacheWrite: 0,
		},
		contextWindow: 1000000,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "deepseek-v4-flash-0731",
		name: "DeepSeek V4 Flash 0731",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text"],
		cost: {
			input: 0.14,
			output: 0.28,
			cacheRead: 0.03,
			cacheWrite: 0,
		},
		contextWindow: 1000000,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "glm-5",
		name: "GLM 5",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text"],
		cost: {
			input: 1.0,
			output: 3.0,
			cacheRead: 0.2,
			cacheWrite: 0,
		},
		contextWindow: 200000,
		maxTokens: 128000,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "glm-5.3",
		name: "GLM 5.3",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text"],
		cost: {
			input: 1.0,
			output: 3.0,
			cacheRead: 0.2,
			cacheWrite: 0,
		},
		contextWindow: 1000000,
		maxTokens: 128000,
		thinking: {
			mode: "effort",
			minLevel: Effort.Low,
			maxLevel: Effort.XHigh,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "gpt-5.6-luna",
		name: "GPT 5.6 Luna",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 0.2,
			output: 1.2,
			cacheRead: 0.02,
			cacheWrite: 0,
		},
		contextWindow: 1050000,
		maxTokens: 128000,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "gpt-5.6-terra",
		name: "GPT 5.6 Terra",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 2.0,
			output: 12.0,
			cacheRead: 0.2,
			cacheWrite: 0,
		},
		contextWindow: 1050000,
		maxTokens: 128000,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "gpt-5.6-sol",
		name: "GPT 5.6 Sol",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 5.0,
			output: 30.0,
			cacheRead: 0.5,
			cacheWrite: 0,
		},
		contextWindow: 1050000,
		maxTokens: 128000,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "hunyuan-t1-vision-20250916",
		name: "Hunyuan T1 Vision 20250916",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 0.14,
			output: 0.56,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 40000,
		maxTokens: 24000,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "hy-vision-2.0-instruct",
		name: "Hy Vision 2.0 Instruct",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 0.14,
			output: 0.56,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 44000,
		maxTokens: 16000,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "hy3",
		name: "Hy3",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text"],
		cost: {
			input: 0.8,
			output: 2.4,
			cacheRead: 0.1,
			cacheWrite: 0,
		},
		contextWindow: 256000,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "kimi-k2.6",
		name: "Kimi K2.6",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 0.6,
			output: 3.0,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 262144,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "kimi-k2.7-code",
		name: "Kimi K2.7 Code",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 0.8,
			output: 4.0,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 262144,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "kimi-k2.7-code-highspeed",
		name: "Kimi K2.7 Code Highspeed",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 0.8,
			output: 4.0,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 262144,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "kimi-k3",
		name: "Kimi K3",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 2.8,
			output: 14.0,
			cacheRead: 0.28,
			cacheWrite: 0,
		},
		contextWindow: 1000000,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Low,
			maxLevel: Effort.XHigh,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "kimi/kimi-k2.6",
		name: "Kimi Kimi K2.6",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 0.6,
			output: 3.0,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 262144,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "MiniMax/MiniMax-M2.1",
		name: "Minimax Minimax M2.1",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 0.3,
			output: 1.2,
			cacheRead: 0.03,
			cacheWrite: 0,
		},
		contextWindow: 204800,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "MiniMax/MiniMax-M2.7",
		name: "Minimax Minimax M2.7",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 0.3,
			output: 1.2,
			cacheRead: 0.06,
			cacheWrite: 0,
		},
		contextWindow: 196608,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "qwen3-max",
		name: "Qwen 3 Max",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text"],
		cost: {
			input: 2.0,
			output: 6.0,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 262144,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "qwen-flash",
		name: "Qwen Flash",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text"],
		cost: {
			input: 0.1,
			output: 0.4,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 1000000,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "qwen3-livetranslate-flash",
		name: "Qwen3 Livetranslate Flash",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text"],
		cost: {
			input: 0.1,
			output: 0.4,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 53248,
		maxTokens: 4096,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "qwen3.8-max",
		name: "Qwen 3.8 Max",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 2.0,
			output: 6.0,
			cacheRead: 0.25,
			cacheWrite: 0,
		},
		contextWindow: 1000000,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "ZHIPU/GLM-5",
		name: "Zhipu GLM 5",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text"],
		cost: {
			input: 1.0,
			output: 3.0,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 202752,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
	{
		id: "ZHIPU/GLM-5.1",
		name: "Zhipu GLM 5.1",
		api: "openai-completions",
		provider: "narwal-plan",
		baseUrl: "https://coder.narwal.com/v1",
		reasoning: true,
		input: ["text"],
		cost: {
			input: 1.4,
			output: 4.4,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 202752,
		maxTokens: 131072,
		thinking: {
			mode: "effort",
			minLevel: Effort.Minimal,
			maxLevel: Effort.High,
		},
		compat: {
			supportsDeveloperRole: false,
		},
	},
];
