#!/usr/bin/env bun

import * as fs from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";
import { $ } from "bun";

const GENERATED_FILE = path.join("src", "embedded-client.generated.txt");
const DIST_CLIENT_DIR = path.join("dist", "client");

const GENERATE_FLAG = "--generate";
const RESET_FLAG = "--reset";

function placeholderContent(): string {
	return `/**
 * Embedded stats dashboard bundle for compiled binaries.
 *
 * This file is generated by \`bun --cwd=packages/stats scripts/generate-client-bundle.ts --generate\` during
 * binary builds. The checked-in value is intentionally empty.
 */
export const EMBEDDED_CLIENT_ARCHIVE_TAR_GZ_BASE64 = "";
`;
}

async function collectFiles(dir: string): Promise<string[]> {
	const entries = await fs.readdir(dir, { withFileTypes: true });
	const files: string[] = [];
	for (const entry of entries) {
		const fullPath = path.join(dir, entry.name);
		if (entry.isDirectory()) {
			files.push(...(await collectFiles(fullPath)));
		} else if (entry.isFile()) {
			files.push(fullPath);
		}
	}
	files.sort((a, b) => a.localeCompare(b));
	return files;
}

async function buildArchiveBase64(dir: string): Promise<string> {
	const files = await collectFiles(dir);
	const entries: Record<string, Uint8Array> = {};
	for (const filePath of files) {
		const relativePath = path.relative(dir, filePath).split(path.sep).join("/");
		entries[relativePath] = await fs.readFile(filePath);
	}

	const tempArchivePath = path.join(
		os.tmpdir(),
		`omp-stats-client-${Bun.hash(Date.now().toString() + Math.random().toString(16)).toString(16)}.tar.gz`,
	);
	try {
		await Bun.Archive.write(tempArchivePath, entries, { compress: "gzip" });
		const archiveBytes = await Bun.file(tempArchivePath).bytes();
		return Buffer.from(archiveBytes).toString("base64");
	} finally {
		await fs.rm(tempArchivePath, { force: true });
	}
}

async function main(): Promise<void> {
	if (process.argv.includes(RESET_FLAG)) {
		await Bun.write(GENERATED_FILE, placeholderContent());
		console.log(`Reset ${GENERATED_FILE}`);
		return;
	}

	if (!process.argv.includes(GENERATE_FLAG)) {
		console.log(`Skipping ${GENERATED_FILE}; pass ${GENERATE_FLAG} to build the embedded bundle`);
		return;
	}

	// 并行竞争防护：`bun run --workspaces build` 时 stats 的 build 与
	// coding-agent 的 build（本脚本）同时操作 dist/client。本脚本不再自己
	// 触发 build，而是等待并行 stats build 产出完整 dist/client
	// （index.js + index.html 均存在，且连续 1s 稳定）；超时（独立运行、
	// 无并行 build 时）再自行构建兑底。
	const BUILD_READY_TIMEOUT_MS = 120_000;
	const deadline = Date.now() + BUILD_READY_TIMEOUT_MS;
	let ready = false;
	while (Date.now() < deadline) {
		const hasIndexJs = await fs
			.access(path.join(DIST_CLIENT_DIR, "index.js"))
			.then(() => true)
			.catch(() => false);
		const hasIndexHtml = await fs
			.access(path.join(DIST_CLIENT_DIR, "index.html"))
			.then(() => true)
			.catch(() => false);
		if (hasIndexJs && hasIndexHtml) {
			// 稳定窗口：并行 build 可能正在 rm+重建，文件齐全后等 1s 确认
			// 没有再次被 rm（stats build 只 rm 一次，完成后不再动 dist/client）。
			await Bun.sleep(1_000);
			const stillThere = await fs
				.access(path.join(DIST_CLIENT_DIR, "index.js"))
				.then(() => true)
				.catch(() => false);
			if (stillThere) {
				ready = true;
				break;
			}
		} else {
			await Bun.sleep(250);
		}
	}
	if (!ready) {
		console.log("dist/client not ready after wait; building stats client inline");
		await $`bun run build`;
	}

	const archiveBase64 = await buildArchiveBase64(DIST_CLIENT_DIR);
	await Bun.write(GENERATED_FILE, archiveBase64);
	console.log(`Generated ${GENERATED_FILE}`);
}

await main();
